import {test,expect} from './support/fixtures';
import {accountPassword,createWorkspace,signIn} from './support/identity';
import {emailLink} from './support/inbox';

test('real passkey: enrollment, restricted password session, signed sign-in and password-reset preservation',async({page,browser})=>{
  test.setTimeout(180_000);
  const identity=await createWorkspace(page,browser,'supplier');
  const cdp=await page.context().newCDPSession(page);
  await cdp.send('WebAuthn.enable');
  await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
  await page.goto('/account/passkeys');
  await page.getByLabel('Passkey name').fill('Browser regression key');
  await page.getByLabel('Current password',{exact:true}).fill(accountPassword);
  await page.getByRole('button',{name:'Enroll passkey',exact:true}).click();
  await expect(page).toHaveURL(/\/home/);
  expect((await (await page.request.get('/api/me')).json()).mfa).toMatchObject({enrolled:true,verified:true});
  await page.goto('/account/passkeys');
  await page.getByRole('button',{name:'Remove',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Keep at least one key');
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await expect(page).toHaveURL(/\/login/);
  await signIn(page,identity.email,accountPassword);
  await expect(page.getByRole('heading',{name:'Protect your account with a passkey'})).toBeVisible();
  expect((await page.request.get('/api/organizations')).status()).toBe(403);
  await page.getByRole('button',{name:'Verify passkey and continue',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Protect your account with a passkey'})).toHaveCount(0);
  expect((await page.request.get('/api/organizations')).status()).toBe(200);
  await page.goto('/account/passkeys');await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.goto('/forgot-password');await page.getByLabel('Work email').fill(identity.email);
  await page.getByRole('button',{name:'Send reset instructions',exact:true}).click();
  const mail=await emailLink(identity.email,'reset');await page.goto(mail.link);
  const changed='ChangedPasskeyPassword456!';
  await page.getByLabel('New password',{exact:true}).fill(changed);await page.getByLabel('Confirm new password',{exact:true}).fill(changed);
  await page.getByRole('button',{name:'Set new password',exact:true}).click();
  await signIn(page,identity.email,changed);
  await expect(page.getByRole('heading',{name:'Protect your account with a passkey'})).toBeVisible();
  expect((await page.request.get('/api/organizations')).status()).toBe(403);
  await page.getByRole('button',{name:'Verify passkey and continue',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Protect your account with a passkey'})).toHaveCount(0);
  expect((await page.request.get('/api/organizations')).status()).toBe(200);
});
