import { test, expect } from './support/fixtures';
import { createWorkspace } from './support/identity';
import { emptyPdfFixture } from './support/pdfFixture';

test('empty supplier chooses conventional inventory and attaches proof to the actual record', async ({ page, browser }) => {
  test.setTimeout(180_000);
  await createWorkspace(page, browser, 'supplier');
  await page.goto('/supply/new');
  await expect(page.getByTestId('supply-path-choice')).toBeVisible();
  await page.getByRole('button', { name: 'Create inventory', exact: true }).click();
  await page.getByLabel('Commodity or material', { exact: true }).fill('peanut');
  await page.getByLabel('Quantity (kg)', { exact: true }).fill('10');
  await page.getByLabel('Country of origin (ISO code)', { exact: true }).fill('GH');
  const createdEvent = page.waitForResponse(r => r.url().endsWith('/api/inventory/direct') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Create inventory', exact: true }).click();
  const createdResponse = await createdEvent;
  expect(createdResponse.status()).toBe(201);
  const inventory = await createdResponse.json();
  expect(await (await page.request.get('/api/farms')).json()).toEqual([]);
  await page.goto(`/evidence/contribute?entityType=batch&entityId=${inventory.id}`);
  await expect(page.getByLabel('Evidence record', { exact: true })).toHaveValue(inventory.id);
  await page.getByLabel('Document purpose', { exact: true }).selectOption('weighing_ticket');
  await page.getByLabel('Evidence explanation', { exact: true }).fill('Ten kilograms measured at the source warehouse.');
  await page.getByLabel('Evidence file', { exact: true }).setInputFiles({ name: 'quantity.pdf', mimeType: 'application/pdf', buffer: emptyPdfFixture() });
  await page.getByRole('button', { name: 'Attach evidence', exact: true }).click();
  await expect(page.getByText(/Evidence attached to peanut/)).toBeVisible();
  const records = await (await page.request.get(`/api/evidence?entityType=batch&entityId=${inventory.id}`)).json();
  expect(records.some((item: { linked_entity_id: string; type: string }) => item.linked_entity_id === inventory.id && item.type === 'weighing_ticket')).toBe(true);
  await page.reload();
  await expect(page.getByLabel('Evidence record', { exact: true })).toHaveValue(inventory.id);
});

test('source farm and plot do not create inventory until a real harvest is recorded', async ({ page, browser }) => {
  test.setTimeout(180_000);
  await createWorkspace(page, browser, 'supplier');
  await page.goto('/supply/new');
  await page.getByRole('button', { name: 'Register source', exact: true }).click();
  await page.getByRole('button', { name: '+ Create Farm', exact: true }).first().click();
  await page.getByPlaceholder('Farm name *', { exact: true }).fill('Browser source farm');
  await page.getByPlaceholder('Region *', { exact: true }).fill('Northern');
  await page.getByPlaceholder('District *', { exact: true }).fill('Tamale');
  const farmEvent = page.waitForResponse(r => r.url().endsWith('/api/farms') && r.request().method() === 'POST');
  await page.locator('.modal').getByRole('button', { name: 'Create Farm', exact: true }).click();
  const farmResponse = await farmEvent;
  expect(farmResponse.status()).toBe(201);
  const farm = await farmResponse.json();
  await page.getByRole('button', { name: '+ Add Plot', exact: true }).click();
  await page.getByPlaceholder('Plot code * (e.g. PLOT-A-01)', { exact: true }).fill('SOURCE-1');
  await page.getByPlaceholder('Area (hectares) *', { exact: true }).fill('10');
  await page.getByPlaceholder('GPS Lat', { exact: true }).fill('9.4');
  await page.getByPlaceholder('GPS Lng', { exact: true }).fill('-0.8');
  await page.locator('.modal').getByRole('button', { name: 'Add Plot', exact: true }).click();
  await expect(page.getByText('Source ready', { exact: true })).toBeVisible();
  expect(await (await page.request.get('/api/batches')).json()).toEqual([]);
  await page.goto('/batches');
  await page.getByRole('button', { name: '+ Create Batch', exact: true }).first().click();
  await page.locator('.modal select').selectOption(farm.id);
  await page.locator('.modal input[type=date]').fill(new Date().toISOString().slice(0, 10));
  await page.getByPlaceholder('Quantity (kg) *', { exact: true }).fill('100');
  const batchEvent = page.waitForResponse(r => r.url().endsWith('/api/batches') && r.request().method() === 'POST');
  await page.locator('.modal').getByRole('button', { name: 'Create Batch', exact: true }).click();
  const batchResponse = await batchEvent;
  expect(batchResponse.status()).toBe(201);
  const batch = await batchResponse.json();
  expect(batch.farm_id).toBe(farm.id);
  await page.goto(`/farms/${farm.id}`);
  await page.getByRole('button', { name: 'Add supporting evidence', exact: true }).click();
  await expect(page.getByLabel('Evidence record', { exact: true })).toHaveValue(farm.id);
  await expect(page.getByTestId('evidence-context')).toContainText('Browser source farm');
});

test('buyer structures a changed commodity and saves reviewed quantity instead of sample data', async ({ page, browser }) => {
  test.setTimeout(180_000);
  await createWorkspace(page, browser, 'buyer');
  await page.goto('/source/new');
  await page.getByLabel('Sourcing brief', { exact: true }).fill('I need 35 metric tons of organic shea nuts from Ghana, FOB Tema.');
  await page.getByRole('button', { name: 'Structure requirements', exact: true }).click();
  await expect(page.getByLabel('Quantity (kg)', { exact: true })).toHaveValue('35000');
  await page.getByLabel('Quantity (kg)', { exact: true }).fill('36000');
  await page.getByLabel('Delivery location', { exact: true }).fill('Tema');
  await page.getByLabel('Visibility', { exact: true }).selectOption('private');
  const savedEvent = page.waitForResponse(r => r.url().endsWith('/api/sourcing-requests') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Save private draft', exact: true }).click();
  const savedResponse = await savedEvent;
  expect(savedResponse.status()).toBe(201);
  const saved = await savedResponse.json();
  await page.reload();
  const requests = await (await page.request.get('/api/sourcing-requests')).json();
  const persisted = requests.find((item: { id: string }) => item.id === saved.id);
  expect(persisted).toBeTruthy();
  expect(Number(persisted.quantity_kg)).toBe(36000);
  expect(persisted.commodity).toContain('shea');
});


test('contribution onboarding explains missing records and a failed read never enables upload', async ({ page, browser }) => {
  test.setTimeout(180_000);
  await createWorkspace(page, browser, 'supplier');
  await page.goto('/onboarding');
  await page.getByRole('button', { name: 'Show me how it works', exact: true }).click();
  await page.getByRole('button', { name: /Add evidence to a record/ }).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Enter my workspace', exact: true }).click();
  await expect(page).toHaveURL(/\/evidence\/contribute$/);
  await expect(page.getByTestId('supply-path-choice')).toBeVisible();
  await expect(page.getByLabel('Evidence file', { exact: true })).toHaveCount(0);
  await page.route('**/api/farms', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Unavailable' }) }));
  await page.goto('/evidence/contribute?entityType=farm');
  await expect(page.getByRole('alert')).toContainText('Records could not be loaded');
  await expect(page.getByRole('button', { name: 'Attach evidence', exact: true })).toHaveCount(0);
  await expect(page.getByTestId('supply-path-choice')).toHaveCount(0);
});
