// Expand this list as feature modules acquire maintainers and debt is repaired.
export const formattedPaths = [
  'eslint.config.mjs',
  'web/src/i18n/**/*.ts',
  'web/src/i18n/**/*.tsx',
  'scripts/locale.test.mjs',
  'scripts/check-container-security.mjs',
  'scripts/check-container-security.test.mjs',
  'api/scripts/check-runtime-image.mjs',
  'scripts/check-dependencies.mjs',
  'scripts/check-dependencies.test.mjs',
  'security/dependency-exceptions.json',
  '.prettierrc.json',
  'scripts/quality-scope.mjs',
  'scripts/run-format-check.mjs',
  'scripts/check-script-contracts.mjs',
  'scripts/check-script-contracts.test.mjs',
  'scripts/quality-policy.test.mjs',
  'scripts/run-release-checks.mjs',
  'api/src/services/tradeMoney.ts',
  'api/src/services/tradeMoney.test.ts',
  'api/src/modules/payments/**/*.ts',
  'api/src/modules/delivery/**/*.ts',
  'api/src/modules/cancellation/**/*.ts',
  'api/src/modules/fees/**/*.ts',
];
