import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, Scale, ShieldCheck, TriangleAlert } from 'lucide-react';
import Layout from '../components/layout/Layout';
import { listings } from '../api';
import { Listing } from '../types';
import { SkeletonTable } from '../components/shared/Skeleton';

export default function CompareOffersPage() {
  const navigate = useNavigate();
  const [rows, setRows] = useState<Listing[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { listings.list().then((items) => setRows(items.slice(0, 3))).finally(() => setLoading(false)); }, []);
  const scored = useMemo(() => rows.map((item, index) => ({ item, score: matchScore(item), arrival: index === 0 ? '8 Nov' : index === 1 ? '12 Nov' : '18 Nov', gap: item.organic_claim_status === 'attested' ? (index === 0 ? 'Ready' : 'Check certificate date') : 'Organic proof missing' })).sort((a, b) => b.score - a.score), [rows]);
  if (loading) return <Layout currentPage="source-compare"><SkeletonTable rows={7} cols={4} /></Layout>;
  return <Layout currentPage="source-compare" actions={<button className="btn" onClick={() => navigate('/marketplace')}><ArrowLeft size={14} />Back to supply</button>}>
    <div className="text-[10px] font-bold uppercase tracking-[.18em] text-brand-400">Side-by-side decision</div><h2 className="mt-2 text-3xl font-bold tracking-[-.035em]">Compare price with proof—not price instead of proof.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-text-muted">Commercial terms, requirement fit and evidence gaps use the same comparison. CocoaTrace explains the recommendation; a person awards the business.</p>
    <div className="mt-6 overflow-x-auto rounded-3xl border border-border bg-surface"><table><thead><tr><th>Decision factor</th>{scored.map(({ item }) => <th key={item.id}>{item.farm_name || item.seller_name || 'Verified cocoa'}</th>)}</tr></thead><tbody><tr><td className="font-semibold text-white">Match to request</td>{scored.map(({ item, score }) => <td key={item.id}><span className="badge badge-green">{score}% match</span></td>)}</tr><tr><td className="font-semibold text-white">Available quantity</td>{scored.map(({ item }) => <td key={item.id}>{Number(item.available_quantity_kg).toLocaleString()} kg</td>)}</tr><tr><td className="font-semibold text-white">Indicative price</td>{scored.map(({ item }) => <td key={item.id} className="font-mono text-brand-300">€{Number(item.price_per_kg).toFixed(2)}/kg</td>)}</tr><tr><td className="font-semibold text-white">Organic evidence</td>{scored.map(({ item }) => <td key={item.id}>{item.organic_claim_status === 'attested' ? <span className="inline-flex items-center gap-1 text-green-300"><CheckCircle2 size={14} />Verified</span> : <span className="inline-flex items-center gap-1 text-amber-300"><TriangleAlert size={14} />Incomplete</span>}</td>)}</tr><tr><td className="font-semibold text-white">Origin visibility</td>{scored.map(({ item }) => <td key={item.id}>{item.farm_region ? `${item.farm_region}, Ghana` : item.origin_location || 'Review origin'}</td>)}</tr><tr><td className="font-semibold text-white">Estimated arrival</td>{scored.map(({ item, arrival }) => <td key={item.id}>{arrival}</td>)}</tr><tr><td className="font-semibold text-white">Open assurance issue</td>{scored.map(({ item, gap }) => <td key={item.id}>{gap}</td>)}</tr><tr><td className="font-semibold text-white">Decision</td>{scored.map(({ item }, index) => <td key={item.id}><button className={`btn btn-sm ${index === 0 ? 'btn-primary' : ''}`} onClick={() => navigate(`/listing/${item.id}`)}>{index === 0 ? 'Review recommended' : 'Review lot'}</button></td>)}</tr></tbody></table></div>
    <section className="mt-5 grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center rounded-3xl border border-brand-400/20 bg-brand-400/5 p-5 sm:p-6"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-brand-400 text-emerald-950"><Scale size={20} /></span><div><h3 className="text-sm font-bold">Why the first offer ranks highest</h3><p className="mt-2 text-xs leading-5 text-text-muted">It covers the largest share of the request, has current organic evidence and exposes farm origin. The score never overrides buyer approval, sampling or contractual negotiation.</p></div></div><div className="flex items-center gap-2 text-[10px] text-brand-300"><ShieldCheck size={14} />Evidence-backed recommendation</div></section>
  </Layout>;
}

function matchScore(item: Listing) { let score = 55; if (item.organic_claim_status === 'attested') score += 18; if (item.farm_region) score += 9; if (Number(item.available_quantity_kg) >= 10000) score += 10; if (item.incoterm === 'CIF') score += 6; return Math.min(98, score); }
