import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowRight, Building2, CheckCircle2, FileCheck2, Handshake, PackageCheck, Search, ShieldCheck, Sparkles, Sprout, TriangleAlert } from 'lucide-react';
import Layout from '../components/layout/Layout';
import { contracts, farms, holdings, listings, offers, sourcing, workspace } from '../api';
import { Contract, Farm, Holding, Listing, Offer, SourcingRequest } from '../types';
import { useAuthCtx } from '../components/auth/AuthProvider';

type Mode = 'buy' | 'sell';
import type { TradeAction } from '../components/trading/TradeAction';
type HomeData = { actionsUnavailable?:boolean; listings: Listing[]; requests: SourcingRequest[]; offers: Offer[]; contracts: Contract[]; holdings: Holding[]; farms: Farm[]; actions:TradeAction[] };
const empty: HomeData = { listings: [], requests: [], offers: [], contracts: [], holdings: [], farms: [], actions:[] };

export default function ExperienceHomePage() {
  const { user, canDo, onboarding } = useAuthCtx();
  const navigate = useNavigate();
  const [params, setParams] = useSearchParams();
  const canBuy = canDo('offer.create');
  const canSell = canDo('listing.create');
  const defaultMode: Mode = canBuy && (onboarding?.primary_goal?.startsWith('buy') || user?.orgType === 'importer') ? 'buy' : canSell ? 'sell' : 'buy';
  const requestedMode = params.get('mode') === 'sell' ? 'sell' : params.get('mode') === 'buy' ? 'buy' : (localStorage.getItem(`ct_experience_mode:${user?.id}`) as Mode | null);
  const mode: Mode = requestedMode === 'buy' && canBuy ? 'buy' : requestedMode === 'sell' && canSell ? 'sell' : defaultMode;
  const [data, setData] = useState<HomeData>(empty);
  const [actionError, setActionError] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user?.id) localStorage.setItem(`ct_experience_mode:${user.id}`, mode);
    const safe = <T,>(allowed: boolean, call: () => Promise<T[]>) => allowed ? call().catch(() => []) : Promise.resolve([] as T[]);
    let active=true;
    const load=()=>Promise.all([
        safe(canDo('listing.read'), listings.list), sourcing.list().catch(() => []),
        safe(canDo('offer.respond') || canDo('offer.create'), offers.list), safe(canDo('contract.read'), contracts.list),
        safe(canDo('holding.read') || canDo('holding.create'), holdings.list), safe(canDo('farm.read'), farms.list), workspace.tradeActions().then(rows=>{if(active)setActionError(false);return rows;}).catch(() => {if(active)setActionError(true);return [];}),
      ]).then(([listingRows,requestRows,offerRows,contractRows,holdingRows,farmRows,actionRows])=>{if(active)setData({listings:listingRows,requests:requestRows,offers:offerRows,contracts:contractRows,holdings:holdingRows,farms:farmRows,actions:actionRows});}).finally(()=>{if(active)setLoading(false);});
    load();
    const interval=window.setInterval(load,15000);
    window.addEventListener('focus',load);
    return()=>{active=false;window.clearInterval(interval);window.removeEventListener('focus',load);};
  }, [mode, user?.id]);

  const switchMode = (next: Mode) => { if (user?.id) localStorage.setItem(`ct_experience_mode:${user.id}`, next); setParams({ mode: next }); };
  return <Layout currentPage="home" actions={canBuy && canSell ? <div className="hidden rounded-xl border border-border bg-surface-darker p-1 sm:flex"><ModeButton active={mode === 'buy'} onClick={() => switchMode('buy')} icon={Search}>Buy</ModeButton><ModeButton active={mode === 'sell'} onClick={() => switchMode('sell')} icon={Sprout}>Sell</ModeButton></div> : undefined}>
    {actionError && <div role="alert" className="mb-4 rounded-xl border border-amber-300/30 p-4 text-sm">Trade actions could not be refreshed. Reload the page to retry before continuing a trade.</div>}
    {loading ? <div className="loading"><div className="spinner" />Preparing your workspace…</div> : mode === 'buy' ? <BuyerHome data={{...data,actionsUnavailable:actionError}} organizationId={user?.organizationId || ''} firstName={user?.name?.split(' ')[0] || 'there'} navigate={navigate} /> : <SellerHome data={{...data,actionsUnavailable:actionError}} organizationId={user?.organizationId || ''} firstName={user?.name?.split(' ')[0] || 'there'} navigate={navigate} />}
  </Layout>;
}

function BuyerHome({ data, organizationId, firstName, navigate }: { data: HomeData; organizationId: string; firstName: string; navigate: ReturnType<typeof useNavigate> }) {
  const qualified = data.listings.reduce((sum, item) => sum + Number(item.available_quantity_kg || 0), 0);
  const pendingOffers = data.offers.filter((item) => item.status === 'pending').length;
  const myRequests = data.requests.filter((item) => item.buyer_organization_id === organizationId);
  const activeRequest = myRequests.find((item) => item.status === 'open');
  return <>
    <Hero eyebrow="Evidence-aware procurement" title={`Good ${dayPart()}, ${firstName}. Source raw materials with the right proof.`} copy="Describe what you need once. CocoaTrace matches commodity, quantity, origin, assurance and delivery terms, then preserves the record through fulfilment." action="Create sourcing brief" onClick={() => navigate('/source/new')} />
    <ActionCenter failed={data.actionsUnavailable} actions={data.actions} navigate={navigate} />
    <div className="mt-5 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Qualified supply" value={`${compactKg(qualified)} kg`} note={`${data.listings.length} published lots`} /><Metric label="Open sourcing needs" value={String(myRequests.filter((item) => item.status === 'open').length)} note="matched suppliers can respond" /><Metric label="Offers to decide" value={String(pendingOffers)} note="price and assurance together" /><Metric label="Active orders" value={String(data.contracts.length)} note="commercial + trace record" /></div>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.08fr_.92fr]"><Panel eyebrow="Sourcing setup" title="Move procurement forward">{activeRequest ? <Task icon={Search} title={`Review matches for ${activeRequest.commodity}`} copy={`${Number(activeRequest.quantity_kg).toLocaleString()} kg requested for ${activeRequest.delivery_location}. Results are ranked against these requirements.`} action="Review matches" onClick={() => navigate(`/marketplace?request=${activeRequest.id}`)} /> : <Task icon={FileCheck2} title="Describe your sourcing need" copy="Create a structured, editable request before reviewing supply." action="Create brief" onClick={() => navigate('/source/new')} />}{data.contracts[0] && <Task icon={Handshake} title="Continue the active deal" copy="Payment, documents and transport actions stay in one guided record." action="Deal room" onClick={() => navigate(`/deal-room/${data.contracts[0].id}`)} />}</Panel><Copilot title="Recommendation based on your records" text={activeRequest ? `Your open request is for ${activeRequest.commodity}. Review its matched results; any quantity, origin or assurance gaps will be shown explicitly.` : 'Create a sourcing brief first. The reviewed fields become the request used to rank marketplace supply.'} /></section>
    <Journey active={1} labels={['Define need', 'Match supply', 'Review proof', 'Contract', 'Receive']} />
  </>;
}

function SellerHome({ data, organizationId, firstName, navigate }: { data: HomeData; organizationId: string; firstName: string; navigate: ReturnType<typeof useNavigate> }) {
  const inventory = data.holdings.filter((item) => item.status === 'available').reduce((sum, item) => sum + Number(item.quantity_kg || 0), 0);
  const received = data.offers.filter((item) => item.status === 'pending').length;
  const myListings = data.listings.filter((item) => item.seller_organization_id === organizationId);
  const commodities = new Set(data.holdings.map((item) => normalizedCommodity(item.crop)));
  const openRequest = data.requests.find((item) => item.status === 'open' && item.buyer_organization_id !== organizationId && commodities.has(normalizedCommodity(item.commodity)));
  const hasInventory = data.holdings.length > 0; const hasFarm = data.farms.length > 0;
  const guidedStart = localStorage.getItem('ct_guided_fresh_start') === 'sell';
  const showSetupChoice = guidedStart || (!hasInventory && !hasFarm);
  const startSupply = (path: string) => { localStorage.removeItem('ct_guided_fresh_start'); navigate(path); };
  const goHero = () => document.getElementById(showSetupChoice ? 'supplier-path' : 'create-supply')?.scrollIntoView({ behavior: 'smooth' });
  return <>
    <Hero eyebrow="Market access" title={`Good ${dayPart()}, ${firstName}. Turn inventory into buyer-ready supply.`} copy="Choose the evidence path that matches the material you actually sell. Organic or origin-verified supply starts at source; conventional supply starts with inventory." action={showSetupChoice ? 'Choose how to create supply' : 'Create new supply'} onClick={goHero} />
    <ActionCenter failed={data.actionsUnavailable} actions={data.actions} navigate={navigate} />
    <div className="mt-5 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Available inventory" value={`${compactKg(inventory)} kg`} note="physical and uncommitted" /><Metric label="Published supply" value={String(myListings.length)} note="visible to qualified buyers" /><Metric label="Matching buyer requests" value={String(data.requests.filter((item) => item.status === 'open' && item.buyer_organization_id !== organizationId && commodities.has(normalizedCommodity(item.commodity))).length)} note="compatible with your inventory" /><Metric label="Offers received" value={String(received)} note="awaiting commercial decision" /></div>
    <section id="supplier-path" className="mt-5 grid gap-5 xl:grid-cols-[1.08fr_.92fr]">
      <Panel eyebrow={data.actions.length ? "Supply setup · separate from active trades" : "Start your supply journey"} title={showSetupChoice ? 'How will you sell this material?' : 'Continue your supply journey'}>
        {showSetupChoice ? <>
          <Task icon={Sprout} title="Organic or origin-verified supply" copy="Register the source farm and plots, then record the harvest. Use this when field-level provenance is part of the claim." action="Start with source" onClick={() => startSupply('/farms')} />
          <Task icon={PackageCheck} title="Conventional supply" copy="Record commercial inventory directly. No farm, plot or organic claim will be invented." action="Create inventory" onClick={() => startSupply('/inventory/new')} />
        </> : hasFarm && !hasInventory ? <Task icon={PackageCheck} title="Record the harvested quantity" copy="Your source is registered. Create the batch that becomes available inventory." action="Record harvest" onClick={() => navigate('/batches')} /> : received ? <Task icon={Handshake} title="Review the new buyer offer" copy="Decide on the commercial offer before any contract is created." action="Review offer" onClick={() => navigate('/offers')} /> : myListings.length === 0 ? <Task icon={PackageCheck} title="Publish available inventory" copy={`You have ${compactKg(inventory)} kg available. Add price, quantity, Incoterm and destination.`} action="Publish supply" onClick={() => navigate('/supply/new')} /> : openRequest ? <Task icon={Building2} title={`Demand for ${openRequest.commodity}`} copy={`${Number(openRequest.quantity_kg).toLocaleString()} kg · ${openRequest.incoterm} ${openRequest.delivery_location}. This is shown because it matches your recorded commodity.`} action="Review your listing" onClick={() => navigate('/my-listings')} /> : <Task icon={PackageCheck} title="Keep published supply current" copy="No compatible open buyer request is recorded. Your listing remains visible without presenting unrelated demand." action="View listings" onClick={() => navigate('/my-listings')} />}
      </Panel>
      <Copilot title="Why this is next" text={showSetupChoice ? 'Choose the path based on the claim you can support. Organic and field-origin supply needs source records; conventional supply does not.' : hasFarm && !hasInventory ? 'A farm alone is not sellable inventory. Record the quantity harvested from it next.' : myListings.length === 0 ? 'Inventory is recorded but not visible to buyers. Publishing it is the next dependency.' : received ? 'A buyer is waiting for your decision. Accepting creates the guided contract workflow.' : 'Your supply is published. Only compatible demand and real buyer actions will appear here.'} />
    </section>
    {!showSetupChoice && <section id="create-supply" className="mt-5"><Panel eyebrow="Create another supply" title="Choose the evidence path for the new material"><Task icon={Sprout} title="Organic or origin-verified supply" copy="Create a source farm and plots before recording the harvest." action="Register source" onClick={() => startSupply('/farms')} /><Task icon={PackageCheck} title="Conventional supply" copy="Create inventory directly with declared origin and warehouse information." action="Create inventory" onClick={() => startSupply('/inventory/new')} /></Panel></section>}
    <Journey active={!hasInventory ? 0 : myListings.length ? 2 : 1} labels={['Record inventory', 'Publish supply', 'Review offers', 'Fulfil order', 'Build history']} />
  </>;
}

function Hero({ eyebrow, title, copy, action, onClick }: { eyebrow: string; title: string; copy: string; action: string; onClick: () => void }) { return <section className="relative overflow-hidden rounded-3xl border border-brand-400/20 bg-[radial-gradient(circle_at_85%_15%,rgba(109,190,90,.22),transparent_30%),linear-gradient(135deg,#173326,#0e1a14)] p-6 sm:p-8"><div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-brand-300">{eyebrow}</div><h2 className="mt-3 max-w-4xl text-3xl font-bold leading-tight tracking-[-.04em] sm:text-4xl">{title}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-emerald-50/60">{copy}</p></div><button className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-brand-400 px-5 text-sm font-bold text-emerald-950" onClick={onClick}>{action}<ArrowRight size={16} /></button></div></section>; }
function ActionCenter({ actions, navigate, failed }: { failed?:boolean; actions:TradeAction[]; navigate:ReturnType<typeof useNavigate> }) { if(failed)return null; const visible=actions.slice(0,3); if(!visible.length)return <section className="mt-5 rounded-3xl border border-border p-5" role="status">No active trade actions to show. Use the sourcing or supply setup below to start a new trade.</section>; const required=actions.filter((item)=>item.requiresAction).length; return <section className="mt-5 rounded-3xl border border-brand-400/25 bg-[linear-gradient(135deg,rgba(109,190,90,.10),rgba(255,255,255,.02))] p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-brand-300">Trade action centre · updates automatically</div><h3 className="mt-1 text-xl font-bold">{required?`${required} action${required===1?'':'s'} need your attention`:'Your trades are moving'}</h3></div>{required>0&&<span className="badge badge-amber">Action required</span>}</div><div className="mt-5 space-y-3">{visible.map((item,index)=><button data-testid="dashboard-trade-action" data-contract-id={item.contractId} data-action-id={item.id} key={item.id} onClick={()=>navigate(item.actionPath)} className={`group flex w-full items-center gap-4 rounded-2xl border p-4 text-left transition ${item.requiresAction&&index===0?'border-amber-300/30 bg-amber-300/5 hover:border-amber-300/50':'border-border bg-surface-darker hover:border-brand-400/30'}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-2xl ${item.requiresAction?'bg-amber-300/10 text-amber-300':'bg-brand-400/10 text-brand-400'}`}>{item.requiresAction?<TriangleAlert size={17}/>:<CheckCircle2 size={17}/>}</span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">{item.title}</span><span className="text-[9px] font-bold uppercase tracking-wider text-text-muted">{item.requiresAction?'Your action':'In progress'}</span></span><span className="mt-1 block text-xs leading-5 text-text-muted">{item.description}</span></span><span className="hidden shrink-0 items-center gap-1 text-[10px] font-semibold text-brand-300 sm:flex">{item.actionLabel}<ArrowRight size={12}/></span></button>)}</div></section>; }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <div className="rounded-2xl border border-border bg-surface p-4 sm:p-5"><div className="text-[9px] font-bold uppercase tracking-[.14em] text-text-muted">{label}</div><div className="mt-4 font-mono text-2xl font-bold sm:text-3xl">{value}</div><div className="mt-2 text-[10px] text-text-muted">{note}</div></div>; }
function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <div className="rounded-3xl border border-border bg-surface p-5 sm:p-6"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-brand-400">{eyebrow}</div><h3 className="mt-1 text-lg font-bold">{title}</h3><div className="mt-5 space-y-2">{children}</div></div>; }
function Task({ icon: Icon, title, copy, action, onClick }: { icon: typeof Search; title: string; copy: string; action: string; onClick: () => void }) { return <button onClick={onClick} className="group flex w-full items-center gap-4 rounded-2xl border border-border bg-surface-darker p-4 text-left transition hover:border-brand-400/30"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-brand-400/10 text-brand-400"><Icon size={18} /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{title}</span><span className="mt-1 block text-xs leading-5 text-text-muted">{copy}</span></span><span className="hidden items-center gap-1 text-[10px] font-semibold text-brand-300 group-hover:flex">{action}<ArrowRight size={12} /></span></button>; }
function Copilot({ title, text }: { title: string; text: string }) { return <div className="rounded-3xl border border-brand-400/20 bg-[linear-gradient(145deg,rgba(109,190,90,.1),rgba(255,255,255,.02))] p-5 sm:p-6"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-400 text-emerald-950"><Sparkles size={18} /></span><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-brand-300">Grounded workspace copilot</div><h3 className="mt-1 text-lg font-bold">{title}</h3></div></div><p className="mt-5 border-l-2 border-brand-400 pl-4 text-sm leading-6 text-text-secondary">{text}</p><div className="mt-5 flex items-start gap-3 rounded-2xl bg-black/15 p-4 text-xs leading-5 text-text-muted"><ShieldCheck size={16} className="mt-0.5 shrink-0 text-brand-400" />Recommendations cite recorded facts. AI cannot approve compliance, award a trade or change the product record.</div></div>; }
function Journey({ active, labels }: { active: number; labels: string[] }) { return <section className="mt-5 rounded-3xl border border-border bg-surface p-5 sm:p-6"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-brand-400">Your end-to-end journey</div><div className="mt-5 grid gap-3 md:grid-cols-5">{labels.map((label, index) => <div key={label} className={`rounded-2xl border p-4 ${index <= active ? 'border-brand-400/30 bg-brand-400/5' : 'border-border bg-surface-darker'}`}><div className={`grid h-7 w-7 place-items-center rounded-full text-[10px] font-bold ${index < active ? 'bg-brand-400 text-emerald-950' : index === active ? 'border border-brand-400 text-brand-300' : 'bg-white/5 text-text-muted'}`}>{index < active ? <CheckCircle2 size={14} /> : index + 1}</div><div className="mt-3 text-xs font-semibold">{label}</div>{index === active && <div className="mt-2 flex items-center gap-1 text-[9px] text-amber-300"><TriangleAlert size={11} />Current stage</div>}</div>)}</div></section>; }
function ModeButton({ active, onClick, icon: Icon, children }: { active: boolean; onClick: () => void; icon: typeof Search; children: React.ReactNode }) { return <button onClick={onClick} className={`inline-flex min-h-8 items-center gap-1.5 rounded-lg px-3 text-[11px] font-semibold ${active ? 'bg-white text-emerald-950' : 'text-text-muted hover:text-white'}`}><Icon size={13} />{children}</button>; }
function compactKg(value: number) { return value >= 1000 ? `${(value / 1000).toFixed(value >= 10000 ? 1 : 0)}k` : value.toLocaleString(); }
function dayPart() { const hour = new Date().getHours(); return hour < 12 ? 'morning' : hour < 18 ? 'afternoon' : 'evening'; }
function normalizedCommodity(value?: string) { return (value || '').toLowerCase().replace(/\b(beans?|nuts?|kernels?|raw)\b/g, '').replace(/\s+/g, ' ').trim(); }
