import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, BadgeCheck, CheckCircle2, MapPin, Search, ShieldCheck, SlidersHorizontal, Sparkles, TriangleAlert } from 'lucide-react';
import { listings, sourcing } from '../api';
import { Listing, SourcingRequest } from '../types';
import Layout from '../components/layout/Layout';

export default function MarketplacePage() {
  const navigate = useNavigate();
  const [all, setAll] = useState<Listing[]>([]);
  const [requests, setRequests] = useState<SourcingRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [organicOnly, setOrganicOnly] = useState(true);
  const [sort, setSort] = useState('match');
  const [error, setError] = useState('');
  useEffect(() => { Promise.all([listings.list(), sourcing.list().catch(() => [])]).then(([listingRows, requestRows]) => { setAll(listingRows); setRequests(requestRows); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  const activeRequest = requests.find((item) => item.status === 'open');
  const result = useMemo(() => all.map((item) => ({ item, score: score(item), gaps: gaps(item) })).filter(({ item }) => (!search || `${item.seller_name} ${item.farm_name} ${item.farm_region} ${item.crop}`.toLowerCase().includes(search.toLowerCase())) && (!organicOnly || item.organic_claim_status === 'attested')).sort((a, b) => sort === 'price' ? Number(a.item.price_per_kg) - Number(b.item.price_per_kg) : sort === 'quantity' ? Number(b.item.available_quantity_kg) - Number(a.item.available_quantity_kg) : b.score - a.score), [all, search, organicOnly, sort]);

  return <Layout currentPage="marketplace" actions={<button className="btn btn-primary" onClick={() => navigate('/source/compare')}>Compare shortlisted</button>}>
    <section className="rounded-3xl border border-border bg-surface p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-brand-400">Matched verified supply</div><h2 className="mt-2 text-3xl font-bold tracking-[-.035em]">Evaluate supply before the first email.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-text-muted">Ranking combines commercial fit with documented readiness. Missing proof remains visible and no supplier is described as risk-free.</p></div>{activeRequest ? <div className="rounded-2xl border border-brand-400/20 bg-brand-400/5 p-4 lg:max-w-sm"><div className="text-[9px] font-bold uppercase tracking-[.16em] text-brand-300">Matching your open request</div><div className="mt-2 text-sm font-semibold">{activeRequest.title}</div><div className="mt-1 text-[10px] text-text-muted">{Number(activeRequest.quantity_kg).toLocaleString()} kg · {activeRequest.incoterm} {activeRequest.delivery_location}</div></div> : <button className="btn" onClick={() => navigate('/source/new')}>Create sourcing brief</button>}</div></section>
    <div className="mt-5 flex flex-wrap items-center gap-3"><div className="relative min-w-[240px] flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" /><input className="form-input pl-9" placeholder="Search supply, origin or supplier…" value={search} onChange={(e) => setSearch(e.target.value)} /></div><label className="btn cursor-pointer"><input type="checkbox" checked={organicOnly} onChange={(e) => setOrganicOnly(e.target.checked)} className="accent-[#7dcc61]" />Organic verified</label><button className="btn"><SlidersHorizontal size={14} />Filters</button><select className="form-select w-auto" value={sort} onChange={(e) => setSort(e.target.value)}><option value="match">Best match</option><option value="price">Lowest price</option><option value="quantity">Most available</option></select></div>
    {loading ? <div className="loading"><div className="spinner" />Finding verified supply…</div> : error ? <div className="mt-5 rounded-2xl border border-red-500/30 bg-red-900/10 p-4 text-xs text-red-300">{error}</div> : <div className="mt-5 grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{result.map(({ item, score: match, gaps: issues }) => <article key={item.id} className="group overflow-hidden rounded-3xl border border-border bg-surface transition hover:-translate-y-0.5 hover:border-brand-400/35"><div className="relative h-36 overflow-hidden bg-[radial-gradient(circle_at_80%_10%,rgba(239,190,106,.35),transparent_30%),linear-gradient(145deg,#392317,#8f5b34)] p-4"><div className="flex items-start justify-between"><span className="badge badge-green">{match}% match</span><span className="inline-flex items-center gap-1 rounded-full bg-black/25 px-2.5 py-1 text-[10px] text-white/75"><MapPin size={11} />{item.farm_region || item.origin_location || 'Origin recorded'}</span></div><div className="absolute bottom-4 left-4 flex items-center gap-2 text-[10px] text-white/70"><ShieldCheck size={14} />Field-to-lot trace available</div></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-base font-bold">{item.farm_name || `${item.crop || 'Cocoa'} lot`}</h3><p className="mt-1 text-[11px] text-text-muted">{item.seller_name || 'Verified supplier'} · {Number(item.available_quantity_kg).toLocaleString()} kg available</p></div><MatchRing value={match} /></div><div className="mt-5 flex items-end justify-between border-y border-border py-4"><div><div className="text-[9px] uppercase tracking-wider text-text-muted">Indicative price</div><div className="mt-1 font-mono text-xl font-bold text-brand-300">€{Number(item.price_per_kg).toFixed(2)}<span className="text-[10px] font-normal text-text-muted">/kg</span></div></div><div className="text-right"><div className="text-[9px] uppercase tracking-wider text-text-muted">Delivery</div><div className="mt-1 text-xs font-semibold">{item.incoterm} {item.destination_location || 'Rotterdam'}</div></div></div><div className="mt-4 grid grid-cols-3 gap-2"><Signal ok label="Origin" value={item.farm_region || 'Recorded'} /><Signal ok={item.organic_claim_status === 'attested'} label="Organic" value={item.organic_claim_status === 'attested' ? 'Verified' : 'Review'} /><Signal ok={issues.length === 0} label="Open gaps" value={String(issues.length)} /></div><div className="mt-5 flex gap-2"><button className="btn btn-primary flex-1 justify-center" onClick={() => navigate(`/listing/${item.id}`)}>View verified lot <ArrowRight size={14} /></button><button className="btn" aria-label="Shortlist"><CheckCircle2 size={15} /></button></div></div></article>)}</div>}
    <section className="mt-5 flex items-start gap-4 rounded-3xl border border-border bg-surface-darker p-5"><BadgeCheck size={20} className="mt-0.5 shrink-0 text-brand-400" /><div><div className="text-sm font-bold">“Verified” means inspectable, not guaranteed.</div><p className="mt-1 text-xs leading-5 text-text-muted">Every claim shows its source, reviewer, freshness and unresolved gaps. CocoaTrace preserves evidence and decisions; certification bodies, laboratories and responsible operators retain their authority.</p></div><Sparkles size={18} className="ml-auto hidden text-brand-400 sm:block" /></section>
  </Layout>;
}
function score(item: Listing) { let value = 57; if (item.organic_claim_status === 'attested') value += 18; if (item.farm_region) value += 9; if (Number(item.available_quantity_kg) >= 10000) value += 10; if (item.incoterm === 'CIF') value += 6; return Math.min(98, value); }
function gaps(item: Listing) { const items: string[] = []; if (item.organic_claim_status !== 'attested') items.push('organic'); if (!item.farm_region) items.push('origin'); return items; }
function Signal({ ok, label, value }: { ok: boolean; label: string; value: string }) { return <div className="rounded-xl bg-surface-darker p-3"><div className={`flex items-center gap-1 text-[9px] ${ok ? 'text-brand-300' : 'text-amber-300'}`}>{ok ? <CheckCircle2 size={11} /> : <TriangleAlert size={11} />}{label}</div><div className="mt-1 truncate text-[10px] font-semibold">{value}</div></div>; }
function MatchRing({ value }: { value: number }) { return <div className="relative grid h-11 w-11 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(#7dcc61 ${value * 3.6}deg, rgba(255,255,255,.08) 0)` }}><div className="grid h-8 w-8 place-items-center rounded-full bg-surface font-mono text-[10px] font-bold">{value}</div></div>; }
