import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertCircle, ArrowLeft, ArrowRight, Check, LockKeyhole, Sparkles } from 'lucide-react';
import Layout from '../components/layout/Layout';
import { sourcing } from '../api';
import { StructuredSourcingBrief } from '../types';
import { useToast } from '../components/shared/ToastProvider';

const initialBrief = '20 metric tonnes of fully fermented organic cocoa beans from Ghana. Moisture maximum 7.5%, delivered to Rotterdam by 15 November 2026. Require plot-level origin and an EUDR data pack.';

export default function SourcingBriefPage() {
  const navigate = useNavigate(); const { toast } = useToast();
  const [brief, setBrief] = useState(initialBrief); const [structured, setStructured] = useState<StructuredSourcingBrief | null>(null);
  const [commodity, setCommodity] = useState(''); const [quantity, setQuantity] = useState(''); const [origins, setOrigins] = useState('');
  const [delivery, setDelivery] = useState(''); const [incoterm, setIncoterm] = useState('CIF'); const [requiredBy, setRequiredBy] = useState(''); const [deadline, setDeadline] = useState('');
  const [qualityNotes, setQualityNotes] = useState(''); const [organic, setOrganic] = useState(false); const [plotGeolocation, setPlotGeolocation] = useState(false); const [eudr, setEudr] = useState(false);
  const [visibility, setVisibility] = useState<'matched' | 'private'>('matched'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');

  const structure = async () => { setBusy(true); setError(''); try {
    const result = await sourcing.structure(brief); setStructured(result); setCommodity(result.commodity); setQuantity(result.quantityKg ? String(result.quantityKg) : ''); setOrigins(result.originCountries.join(', ')); setDelivery(result.deliveryLocation); setIncoterm(result.incoterm); setRequiredBy(result.requiredBy);
    setQualityNotes(Object.entries(result.qualityRequirements).map(([key, value]) => `${key}: ${value}`).join('; ')); setOrganic(Boolean(result.assuranceRequirements.organic)); setPlotGeolocation(Boolean(result.assuranceRequirements.plotGeolocation)); setEudr(Boolean(result.assuranceRequirements.eudrDataPack));
  } catch (err: any) { setError(err.message || 'Could not structure the brief'); } finally { setBusy(false); } };
  const requirements = useMemo(() => [
    { title: 'Commodity and quantity', detail: `${commodity || 'Not identified'} · ${quantity ? `${Number(quantity).toLocaleString()} kg` : 'quantity required'}${origins ? ` · ${origins}` : ''}`, ok: Boolean(commodity && Number(quantity)) },
    { title: 'Quality specification', detail: qualityNotes || 'No explicit quality specification extracted; add one if needed.', ok: true },
    { title: 'Assurance package', detail: [organic && 'Organic evidence', plotGeolocation && 'Plot geolocation', eudr && 'EUDR data pack'].filter(Boolean).join(' · ') || 'Conventional supply; no special assurance selected', ok: true },
    { title: 'Commercial delivery', detail: `${incoterm} ${delivery || 'location required'}${requiredBy ? ` · required ${requiredBy}` : ''}`, ok: Boolean(delivery) },
  ], [commodity, quantity, origins, qualityNotes, organic, plotGeolocation, eudr, incoterm, delivery, requiredBy]);
  const publish = async () => { setBusy(true); setError(''); try {
    if (!structured) throw new Error('Structure and review the requirements before continuing.'); if (!commodity || !Number(quantity) || !delivery) throw new Error('Commodity, quantity and delivery location are required.');
    const status = visibility === 'private' ? 'draft' : 'open'; const request = await sourcing.create({ title: `${organic ? 'Organic ' : ''}${commodity} for ${delivery}`, commodity: commodity.trim().toLowerCase(), quantityKg: Number(quantity), originCountries: origins.split(',').map((value) => value.trim().toUpperCase()).filter(Boolean), qualityRequirements: { notes: qualityNotes }, assuranceRequirements: { organic, plotGeolocation, eudrDataPack: eudr }, deliveryLocation: delivery, incoterm, requiredBy: requiredBy || undefined, offerDeadline: deadline ? new Date(deadline).toISOString() : undefined, visibility, status });
    localStorage.setItem('ct_active_sourcing_request', request.id); toast('success', status === 'draft' ? 'Private sourcing draft saved.' : 'Sourcing request published with your reviewed requirements.'); navigate(status === 'draft' ? '/home?mode=buy' : `/marketplace?request=${request.id}`);
  } catch (err: any) { setError(err.message || 'Could not publish sourcing request'); } finally { setBusy(false); } };

  return <Layout currentPage="source-new" actions={<button className="btn" onClick={() => navigate('/home?mode=buy')}><ArrowLeft size={14} />Back to workspace</button>}><div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]">
    <section><div className="text-[10px] font-bold uppercase tracking-[.18em] text-brand-400">Describe the outcome</div><h2 className="mt-2 text-3xl font-bold tracking-[-.035em]">What do you need to buy?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-text-muted">Write the need in ordinary procurement language. CocoaTrace extracts editable requirements and flags anything it could not identify.</p><div className="mt-6 rounded-3xl border border-border bg-surface p-5 sm:p-6"><label className="form-label">Sourcing brief</label><textarea aria-label="Sourcing brief" className="form-input min-h-36 resize-y leading-6" value={brief} onChange={(event) => { setBrief(event.target.value); setStructured(null); }} /><button className="btn btn-primary mt-4" disabled={busy} onClick={structure}><Sparkles size={15} />{busy ? 'Structuring…' : structured ? 'Restructure requirements' : 'Structure requirements'}</button></div><div className="mt-4 flex items-start gap-3 rounded-2xl border border-border bg-surface-darker p-4 text-xs leading-5 text-text-muted"><LockKeyhole size={16} className="mt-0.5 shrink-0 text-brand-400" />Only the reviewed fields are published. The original text never overrides your edits.</div></section>
    <section className="space-y-4"><div className="rounded-3xl border border-brand-400/20 bg-[linear-gradient(145deg,rgba(109,190,90,.1),rgba(255,255,255,.02))] p-5 sm:p-6"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-400 text-emerald-950"><Sparkles size={18} /></span><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-brand-300">Structured requirements</div><h3 className="mt-1 text-lg font-bold">Review every extracted fact</h3></div></div>{structured && <><div className="mt-5 space-y-2">{requirements.map((item) => <div key={item.title} className="flex gap-3 rounded-2xl border border-border bg-surface-darker p-4"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full ${item.ok ? 'bg-brand-400/10 text-brand-400' : 'bg-amber-300/10 text-amber-300'}`}>{item.ok ? <Check size={14} /> : <AlertCircle size={14} />}</span><div><div className="text-xs font-semibold">{item.title}</div><div className="mt-1 text-[11px] leading-5 text-text-muted">{item.detail}</div></div></div>)}</div>{structured.unresolved.length > 0 && <div className="mt-3 text-[10px] text-amber-300">Review needed: {structured.unresolved.join(', ')}</div>}</>}</div>
    <div className="rounded-3xl border border-border bg-surface p-5 sm:p-6"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-brand-400">Editable request</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Commodity or material"><input className="form-input" value={commodity} onChange={(e) => setCommodity(e.target.value)} /></Field><Field label="Quantity (kg)"><input className="form-input" type="number" value={quantity} onChange={(e) => setQuantity(e.target.value)} /></Field><Field label="Origin country codes"><input className="form-input" placeholder="GH, CI" value={origins} onChange={(e) => setOrigins(e.target.value)} /></Field><Field label="Incoterm"><select aria-label="Incoterm" className="form-select" value={incoterm} onChange={(e) => setIncoterm(e.target.value)}>{['EXW','FCA','FOB','CFR','CIF','CPT','CIP','DAP','DPU','DDP'].map((term) => <option key={term}>{term}</option>)}</select></Field><Field label="Delivery location"><input className="form-input" value={delivery} onChange={(e) => setDelivery(e.target.value)} /></Field><Field label="Required by"><input className="form-input" type="date" value={requiredBy} onChange={(e) => setRequiredBy(e.target.value)} /></Field><Field label="Offer deadline"><input className="form-input" type="datetime-local" value={deadline} onChange={(e) => setDeadline(e.target.value)} /></Field><Field label="Visibility"><select aria-label="Visibility" className="form-select" value={visibility} onChange={(e) => setVisibility(e.target.value as typeof visibility)}><option value="matched">Matched suppliers</option><option value="private">Private draft</option></select></Field></div><label className="mt-4 block"><span className="form-label">Quality requirements</span><textarea className="form-input min-h-20" value={qualityNotes} onChange={(e) => setQualityNotes(e.target.value)} placeholder="Grade, moisture, specification or tests" /></label><div className="mt-4 flex flex-wrap gap-3"><CheckField checked={organic} set={setOrganic} label="Organic evidence" /><CheckField checked={plotGeolocation} set={setPlotGeolocation} label="Plot geolocation" /><CheckField checked={eudr} set={setEudr} label="EUDR data pack" /></div>{error && <div className="mt-4 rounded-xl border border-red-500/30 bg-red-900/10 p-3 text-xs text-red-300">{error}</div>}<button className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-brand-400 px-5 text-sm font-bold text-emerald-950 disabled:opacity-50" onClick={publish} disabled={busy || !structured}>{visibility === 'private' ? 'Save private draft' : 'Find matching supply'} <ArrowRight size={16} /></button></div></section>
  </div></Layout>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="form-label">{label}</span>{children}</label>; }
function CheckField({ checked, set, label }: { checked:boolean; set:(value:boolean)=>void; label:string }) { return <label className="btn cursor-pointer"><input type="checkbox" checked={checked} onChange={(e) => set(e.target.checked)} className="accent-[#7dcc61]" />{label}</label>; }
